# Generated by Django 5.1.3 on 2024-11-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_App', '0003_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
